apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w0ygcs1wj-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:457474f479c2d7c5fc461f877adae33d94f062f1@sha256:ee901494555f1dbf4e9cb75dc3476950e9a80c18ec7f78b150f2f85484b08a04
          name: container-image
